// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uboovmbxjjrywxgxbvxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVib292bWJ4ampyeXd4Z3hidnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDM5NjksImV4cCI6MjA3MzAxOTk2OX0.hKKTdWE34LxXx5V9CnzYIq6cCVCbz91IliL2QEwZybo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});